name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  PS_MODULE_NAME: PSFits
  VERSION_PREFIX: 1.2.${{ github.run_number }}
  VERSION_REV: ${{ github.run_attempt }}
  VERSION_SUFFIX: +${{ github.sha }}
  BUILD_CONF: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c $BUILD_CONF --no-restore --version-suffix $VERSION_SUFFIX -p:VersionPrefix=${VERSION_PREFIX}${VERSION_REV} -p:FileVersion=${VERSION_PREFIX}.${VERSION_REV}
    - name: Publish
      run: dotnet publish -c $BUILD_CONF --no-build 
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: publish-folder
        path: '**/publish/'
        retention-days: 5
  
  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download NuGet packages
      uses: actions/download-artifact@v3
      with:
        name: publish-folder
    - name: Rename publish folder to module folder
      run: mv bin/$BUILD_CONF/*/publish $PS_MODULE_NAME
    - name: Publish to PowerShell gallery
      run: |
        $version = [version]"$($ENV:VERSION_PREFIX).$($ENV:VERSION_REV)"
        Update-ModuleManifest -Path $ENV:PS_MODULE_NAME/$($ENV:PS_MODULE_NAME).psd1 -ModuleVersion $version
        Publish-Module -Path $ENV:PS_MODULE_NAME -NuGetApiKey ${{ secrets.NUGET_API_KEY }} -Verbose 
      shell: pwsh
