name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  PKG_VERSION: 1.${{ github.run_number }}.${{ github.run_attempt }}
  BUILD_CONF: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c $BUILD_CONF --no-restore --version-suffix +${{ github.sha }} -p:VersionPrefix=$PKG_VERSION -p:FileVersion=${PKG_VERSION}.0
    - name: Publish
      run: dotnet publish -c $BUILD_CONF --no-build 
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: publish-folder
        path: '**/publish/'
        retention-days: 5
  
  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download NuGet packages
      uses: actions/download-artifact@v3
      with:
        name: publish-folder
    - name: Rename publish folder to module folder
      run: mv bin/$BUILD_CONF/*/publish PSFits
    - name: Publish to PowerShell gallery
      run: Publish-Module -Path PSFits -NuGetApiKey ${{ secrets.NUGET_API_KEY }} -Verbose 
      shell: pwsh
